#!/bin/bash

## Description: [BASE] Run front task (no matter if its gulp or grunt)
## Usage: front
## Example: "ddev front build OR ddev front watch"

source .ddev/commands/web/.front_env

if [[ $1 = "build" ]]; then
    yarn install --frozen-lockfile
    ${FRONTEND_BUILD}
fi

if [[ $1 = "watch" ]]; then
    yarn install --frozen-lockfile
    ${FRONTEND_WATCH}
fi

if [[ $1 = "build-noci" ]]; then
    ${FRONTEND_BUILD}
fi

if [[ $1 = "watch-noci" ]]; then
    ${FRONTEND_WATCH}
fi
